### PR TITLE
Plugin that converts string to date #803

### PR DESCRIPTION
**Pull request by Kaushik-Iyer**
Solves Issue #803 

This PR adds a plugin that converts given string to a given date format.
I also tried testing it through a pytest file and I got a correct assertion, but I am still not sure if all my code is right
----

**Please** following this checklist to help us incorporate your contribution quickly and easily:

 - [X] Give the same name to the pull request as the name of ticket 
 - [X] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [X] Test your code thoroughly before PR.
 

 - [X] I hereby declare this contribution to be licenced under the [MIT license](https://opensource.org/licenses/MIT)

### CODE REVIEW

**Comment by atompie** [comment]
@Kaushik-Iyer Thank you for you PR. Could you use this library to make sure that broader type of data strings are accepted?

https://dateparser.readthedocs.io/en/latest/
Also there is a Pending — Contributor License Agreement is not signed yet.  Could you click details and sign the CLA.

**Comment by Kaushik-Iyer** [comment]
@atompie  please check the recent commits. I have implemented dateparser module, and it does not need specifying any input date format. I have made converted date to be year month date for uniformity.

this is a example test case that runs currently

image

**Review by atompie — APPROVED** [review]

**Comment by atompie** [comment]
@Kaushik-Iyer THe changes are ok. The last thing I need is a license/cla . Contributor License Agreement is not signed yet. Could you click details and sign the CLA. Without this I can not merge as I do not have your permission to do so.

**Comment by Kaushik-Iyer** [comment]
@atompie  is it showing as signed now?

**Comment by atompie** [comment]
@Kaushik-Iyer Unfortunately not. Have you done this. You have to be logged in with your github account. 

https://github.com/Tracardi/tracardi/assets/16271564/5c38a20a-6ab8-43b6-b87f-9fae82f32f1e

**Comment by Kaushik-Iyer** [comment]
@atompie done I signed it now

**Review by atompie — APPROVED** [review]

**Pull request merged**
