### PR TITLE
Send messages through ClickSend

### PR DESCRIPTION
**Pull request by ghost**
Add ClickSend SMS Plugin (#816)

----

 - [X] Give the same name to the pull request as the name of ticket 
 - [X] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [X] Test your code throughly before PR.

To make clear that you license your contribution under the MIT you have to acknowledge this by using the following check-box.

 - [X] I hereby declare this contribution to be licenced under the [MIT license](https://opensource.org/licenses/MIT)

PRs without ticked MIT license will not be accepted - Sorry.

### CODE REVIEW

**Comment by ghost** [comment]
Hi @atompie , did you get the time to review this PR?

**Comment by atompie** [comment]
Hi I did not but I am going to accept it (so it counts for hacktoberfest) and I will review it and ask you to make changes if needed later.

**Comment by ghost** [comment]
Sure, works for me. Let me know if there are changes. I'll monitor this thread. Thanks!

**Comment by atompie** [comment]
Hi @kokobhara I merged an tested you plugin.It worked out of the box. Good work. I you would like to further contribute to our project I would be very happy. I have one simple plugin pending https://github.com/Tracardi/tracardi/issues/840 if you would like to contribute this one it would be perfect.

**Comment by ghost** [comment]
Sure, I'll definitely take a look. Thank you so much!

**Comment by atompie** [comment]
@kokobhara Please comment on that issue #840 So I can assign you.

**Pull request merged**
