### PR TITLE
Implement a plugin to strip string off the given characters

### PR DESCRIPTION
**Pull request by ghost**
Plugin that strips string from some characters (#804 )
----
 - [X] Give the same name to the pull request as the name of ticket 
 - [X] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [X] Test your code throughly before PR.
 - [X] I hereby declare this contribution to be licenced under the [MIT license](https://opensource.org/licenses/MIT)

### CODE REVIEW

**Review by atompie — APPROVED** [review]

**Comment by atompie** [comment]
@kokobhara Merged and works as expected

Screenshot from 2023-10-10 08-55-52

**Comment by atompie** [comment]
@kokobhara If you would like also to add documentation for it I created a task. https://github.com/Tracardi/tracardi/issues/828

**Comment by ghost** [comment]
Sure, I'll take that up.

**Comment by atompie** [comment]
@kokobhara You have to comment on https://github.com/Tracardi/tracardi/issues/828 so I can assign you. Thnaks

**Pull request merged**
